name: Merge CI
on: [ pull_request ]
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-lates ]
    steps:
      - uses: actions/checkout@v2
      - run: echo " The job was automatically triggered by a ${{ github.event_name}} event."
      - run: python main.py